version: "3.7"

services:
  db:
    image: postgres:13
    networks:
      - listmonk
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    ports:
      - "9000:9000"
    networks:
      - listmonk
    environment:
      - TZ=Etc/UTC
    container_name: listmonk_app
    command: "./listmonk --i18n-dir=/listmonk/i18n --static-dir=/listmonk/static"
    depends_on:
      - db
    volumes:
      - ./i18n:/listmonk/i18n
      - ./static:/listmonk/static
      - ./config.toml:/listmonk/config.toml

networks:
  listmonk:

volumes:
  listmonk-data:
